apiVersion: v1
kind: Service
metadata:
  name: mytest
  labels:
    app: mytest
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: mytest
    tier: mytest
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mytest
  labels:
    app: mytest
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mytest
        tier: mytest
    spec:
      containers:
      - image: rhlnair87/mytest:latest
        name: mytest
        ports:
        - containerPort: 80
          name: mytest
