FROM nginx:latest

COPY index.html /usr/share/nginx/html/index.html
COPY DockerFileEx.jpg /usr/share/nginx/html/DockerFileEx.jpg
#testing the container
RUN apt-get update && apt-get install -yq curl && apt-get clean
WORKDIR /unit-tests
ADD test.sh /unit-tests/test.sh
#RUN bash /unit-tests/test.sh
CMD ["bash", "test.sh"]
